# wrangler.toml

name = "yes-energy-worker"
main = "src/index.ts"

compatibility_date = "2023-01-01"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "yes-energy-db"
database_id = "e668ac1d-6d8f-41ec-89f9-8d92b48cfc5a"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "yes-energy-forecasts"